name: Build and publish

on:
    push:
        tags:
            - "*"

env:
    SQLITE_RELEASE_YEAR: "2021"
    SQLITE_VERSION: "3340100"

jobs:
    build:
        name: Build for ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                include:
                    - os: ubuntu-latest
                      artifact_extension: .so
                    - os: windows-latest
                      artifact_extension: .dll
                    - os: macos-latest
                      artifact_extension: .dylib

        steps:
            - uses: actions/checkout@v2

            - name: Download SQLite sources
              shell: bash
              run: |
                  curl -L http://sqlite.org/$SQLITE_RELEASE_YEAR/sqlite-amalgamation-$SQLITE_VERSION.zip --output src.zip
                  unzip src.zip
                  mv sqlite-amalgamation-$SQLITE_VERSION/* src
                  mkdir -p dist

            - name: Download native SQLite extensions
              shell: bash
              run: |
                  curl -L https://github.com/sqlite/sqlite/raw/master/ext/misc/json1.c --output src/sqlite3-json1.c

            - name: Build for Linux
              if: matrix.os == 'ubuntu-latest'
              run: |
                  gcc -fPIC -shared src/sqlite3-json1.c -o dist/json1.so -lm
                  gcc -fPIC -shared src/sqlite3-math.c -o dist/math.so -lm
                  gcc -fPIC -shared src/sqlite3-re.c src/re.c -o dist/re.so -lm
                  gcc -fPIC -shared src/sqlite3-stats.c -o dist/stats.so -lm
                  gcc -fPIC -shared src/sqlite3-text.c -o dist/text.so -lm
                  gcc -fPIC -shared src/sqlite3-unicode.c -o dist/unicode.so -lm
                  gcc -fPIC -shared src/sqlite3-vsv.c -o dist/vsv.so -lm

            - name: Build for Windows
              if: matrix.os == 'windows-latest'
              run: |
                  gcc -shared -I. src/sqlite3-json1.c -o dist/json1.dll
                  gcc -shared -I. src/sqlite3-math.c -o dist/math.dll
                  gcc -shared -I. src/sqlite3-re.c src/re.c -o dist/re.dll
                  gcc -shared -I. src/sqlite3-stats.c -o dist/stats.dll
                  gcc -shared -I. src/sqlite3-text.c -o dist/text.dll
                  gcc -shared -I. src/sqlite3-unicode.c -o dist/unicode.dll
                  gcc -shared -I. src/sqlite3-vsv.c -o dist/vsv.dll

            - name: Build for macOS
              if: matrix.os == 'macos-latest'
              run: |
                  gcc -fPIC -dynamiclib -I src src/sqlite3-json1.c -o dist/json1.dylib -lm
                  gcc -fPIC -dynamiclib -I src src/sqlite3-math.c -o dist/math.dylib -lm
                  gcc -fPIC -dynamiclib -I src src/sqlite3-re.c src/re.c -o dist/re.dylib -lm
                  gcc -fPIC -dynamiclib -I src src/sqlite3-stats.c -o dist/stats.dylib -lm
                  gcc -fPIC -dynamiclib -I src src/sqlite3-text.c -o dist/text.dylib -lm
                  gcc -fPIC -dynamiclib -I src src/sqlite3-unicode.c -o dist/unicode.dylib -lm
                  gcc -fPIC -dynamiclib -I src src/sqlite3-vsv.c -o dist/vsv.dylib -lm

            - name: Upload binaries to release
              uses: svenstaro/upload-release-action@v2
              with:
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  file: dist/*
                  file_glob: true
                  tag: ${{ github.ref }}
