name: publish

on:
    push:
        tags:
            - "*"
    workflow_dispatch:

env:
    SQLITE_RELEASE_YEAR: "2021"
    SQLITE_VERSION: "3360000"
    SQLITE_BRANCH: "3.36"

jobs:
    publish:
        name: Publish for ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                include:
                    - os: ubuntu-20.04
                    - os: windows-latest
                    - os: macos-latest

        steps:
            - uses: actions/checkout@v2

            - name: Download SQLite sources
              shell: bash
              run: |
                  make prepare-dist
                  make download-sqlite
                  make download-external

            - name: Build for Linux
              if: matrix.os == 'ubuntu-20.04'
              run: |
                  make compile-linux
                  make pack-linux

            - name: Build for Windows
              if: matrix.os == 'windows-latest'
              shell: bash
              run: |
                  make compile-windows
                  make pack-windows

            - name: Build for macOS
              if: matrix.os == 'macos-latest'
              run: |
                  make compile-macos-x86
                  make compile-macos-arm64
                  make pack-macos

            - name: Upload binaries to release
              uses: svenstaro/upload-release-action@v2
              with:
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  file: dist/*.zip
                  file_glob: true
                  tag: ${{ github.ref }}
